apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  labels:
    cilium-lab/public-service: "true"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ciliumsetup.example.com
  name: grafana
  namespace: cilium-monitoring
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}