apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    cilium-lab/public-service: "true"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ciliumsetup.example.com
  name: prometheus
  namespace: cilium-monitoring
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: webui
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}